#**Netflix Movies and TV Shows: An Exploratory Data Analysis. In this notebook, I will explore the Netflix dataset to understand content trends, popular genres, and the distribution of content across the globe.**

#  Netflix Exploratory Data Analysis (EDA) – Updated till 2025

## 🔹 Introduction
Netflix is one of the largest streaming platforms, offering thousands of Movies and TV Shows globally.  
This project analyzes Netflix data till **2025**, providing more updated insights than traditional 2021 datasets.

## 🔹 Objectives
- Clean and preprocess the dataset
- Explore patterns in Movies vs TV Shows
- Analyze trends across countries and years
- Study popular genres and ratings
- Derive insights on how Netflix’s strategy evolved till 2025

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 🔹 Dataset Description
We have two separate CSV files:
- **Movies dataset**
- **TV Shows dataset**

Each dataset includes:
- `title` – Name of the content  
- `director`, `cast` – Key people involved  
- `country` – Origin country  
- `release_year` – Original release year  
- `date_added` – When added to Netflix  
- `rating` – Age rating (PG, R, TV-MA, etc.)  
- `duration` – Runtime (Movies) or Seasons (TV Shows)  
- `listed_in` – Genres  
- `description` – Short summary

In [ ]:
#Importing Necessary Libararies
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#Style for plots
sns.set_style('whitegrid')
plt.style.use('fivethirtyeight')

# Load the Netflix dataset
movies = pd.read_csv("/content/drive/MyDrive/1230280501028 (1)/Projects/Netflix_Analysis/netflix_movies_detailed_up_to_2025.csv")
tv_shows=pd.read_csv("/content/drive/MyDrive/1230280501028 (1)/Projects/Netflix_Analysis/netflix_tv_shows_detailed_up_to_2025.csv")

df=pd.concat([movies,tv_shows],axis=0)
df.columns
print("Shape of Dataset: ",df.shape)
df

Shape of Dataset:  (32000, 18)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000.0,752600867.0
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000.0,839030630.0
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000.0,954305868.0
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,"Animation, Family, Adventure",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000.0,592461732.0
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,"Fantasy, Adventure, Animation, Family",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000.0,494879471.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,284892,TV Show,Sammelanam,NaN,NaN,NaN,2025-02-20,2025,0.000,1 Seasons,"Comedy, Drama",te,Sammelanam is a gripping Telugu web series tha...,3.236,0,0.000,NaN,NaN
15996,277665,TV Show,Anne Shirley,NaN,"Honoka Inoue, Yasunori Matsumoto, Aya Nakamura...",Japan,2025-04-05,2025,0.000,1 Seasons,"Animation, Drama, Family",ja,It's depict Anne's growth from a girl to a wom...,3.558,0,0.000,NaN,NaN
15997,284972,TV Show,Le onde del passato,Giulio Manfredonia,"Anna Valle, Giorgio Marchesi, Irene Ferri, Fau...",NaN,2025-02-19,2025,10.000,1 Seasons,Drama,it,NaN,2.913,1,10.000,NaN,NaN
15998,284613,TV Show,AI히치하이커,NaN,NaN,NaN,2025-02-16,2025,0.000,1 Seasons,NaN,ko,NaN,2.787,0,0.000,NaN,NaN
15999,251815,TV Show,Alex & Laura's Saturday Night Takeaway,NaN,"Alex Bickerton, Lauren Blake",NaN,2025-02-15,2025,0.000,1 Seasons,"Comedy, Family",en,A gameshow hosted by Alex & Laura filled with ...,2.485,0,0.000,NaN,NaN

In [ ]:
df.info()
#Checking Number of Missing Values in each Row
missing_values=df.isnull().sum()
print('\n Missing Values:\n','\n',missing_values[missing_values>0])

<class 'pandas.core.frame.DataFrame'>
Index: 32000 entries, 0 to 15999
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       32000 non-null  int64
 1   type          32000 non-null  object
 2   title         32000 non-null  object
 3   director      20903 non-null  object
 4   cast          30639 non-null  object
 5   country       29737 non-null  object
 6   date_added    32000 non-null  object
 7   release_year  32000 non-null  int64
 8   rating        32000 non-null  float64
 9   duration      16000 non-null  object
 10  genres        30919 non-null  object
 11  language      32000 non-null  object
 12  description   28662 non-null  object
 13  popularity    32000 non-null  float64
 14  vote_count    32000 non-null  int64
 15  vote_average  32000 non-null  float64
 16  budget        16000 non-null  float64
 17  revenue       16000 non-null  float64
dtypes: float64(5), int64(3), object(10)
memory usage: 5.6+ MB

 Missing Values:

 director       11097
cast            1361
country         2263
duration       16000
genres          1081
description     3338
budget         16000
revenue        16000
dtype: int64

Here, 8 Columns are there which have Missing Values:
director(object),
cast(object),
country(object),
duration(object),
genre(object),
description(object),
budget(object),
revenue(object),



*   **Duration data is only available for TV Show. for Movies These field is Missing.**
*   **Budget and revenue data is only available for Movies. For TV
Shows, these fields are missing.**

## 🔹 Data Cleaning
Steps performed:
1. Handle missing values
2. Convert `date_added` into datetime
3. Extract useful features (`year_added`, `content_age`)
4. Remove duplicates

In [ ]:
df.isnull().sum()

df.fillna({"director":"Unknown",'cast':"Unknown","country":"Unknown",'genres':"Unknown","description":"No Description Available"})

split_duration=df['duration'].str.split(' ',expand=True)

season_num=np.where(df['type']=='TV Show',split_duration[0],np.nan)
df['season_num']=pd.to_numeric(season_num,errors='coerce')

movie_duration=np.where(df['type']=='Movie',split_duration[0],np.nan)
df['movie_duration']=pd.to_numeric(movie_duration,errors='coerce')

df['budget']=pd.to_numeric(df['budget'])

df['revenue']=pd.to_numeric(df['revenue'])

For TV Shows there are no such columns like revenue and budget. but in movies it is there.so there NaNs in tv shows.

In [ ]:
profit=df['revenue']-df['budget']
ROI=profit/df['budget']
df['profit']=profit
df['ROI']=ROI
df.head(15)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,description,popularity,vote_count,vote_average,budget,revenue,season_num,movie_duration,profit,ROI
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,...,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000.0,7.526009e+08,NaN,NaN,587600867.0,3.561217
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,...,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000.0,8.390306e+08,NaN,NaN,679030630.0,4.243941
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,...,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000.0,9.543059e+08,NaN,NaN,704305868.0,2.817223
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,...,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000.0,5.924617e+08,NaN,NaN,332461732.0,1.278699
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,...,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000.0,4.948795e+08,NaN,NaN,329879471.0,1.999270
5,11324,Movie,Shutter Island,Martin Scorsese,"Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley,...",United States of America,2010-02-14,2010,8.200,NaN,...,World War II soldier-turned-U.S. Marshal Teddy...,101.551,24282,8.200,80000000.0,2.948042e+08,NaN,NaN,214804195.0,2.685052
6,38575,Movie,The Karate Kid,Harald Zwart,"Jaden Smith, Jackie Chan, Taraji P. Henson, We...","China, Hong Kong, United States of America",2010-06-10,2010,6.500,NaN,...,Twelve-year-old Dre Parker could have been the...,96.385,6082,6.500,40000000.0,3.591260e+08,NaN,NaN,319126022.0,7.978151
7,10138,Movie,Iron Man 2,Jon Favreau,"Robert Downey Jr., Gwyneth Paltrow, Don Cheadl...",United States of America,2010-04-28,2010,6.800,NaN,...,With the world now aware of his dual life as t...,95.255,21222,6.800,200000000.0,6.239333e+08,NaN,NaN,423933331.0,2.119667
8,38365,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States of America,2010-06-24,2010,6.394,NaN,...,After their high school basketball coach passe...,93.281,6212,6.394,80000000.0,2.714302e+08,NaN,NaN,191430189.0,2.392877
9,48650,Movie,Room in Rome,Julio Medem,"Elena Anaya, Natasha Yarovenko, Enrico Lo Vers...","France, Spain",2010-05-07,2010,6.416,NaN,...,A hotel room in the center of Rome serves as t...,90.230,748,6.416,0.0,8.442810e+05,NaN,NaN,844281.0,inf
10,20352,Movie,Despicable Me,"Pierre Coffin, Chris Renaud","Steve Carell, Jason Segel, Miranda Cosgrove, E...",United States of America,2010-07-08,2010,7.200,NaN,...,Villainous Gru lives up to his reputation as a...,86.361,15258,7.200,69000000.0,5.432843e+08,NaN,NaN,474284256.0,6.873685
11,10193,Movie,Toy Story 3,Lee Unkrich,"Tom Hanks, Tim Allen, Joan Cusack, Don Rickles...",United States of America,2010-06-16,2010,7.800,NaN,...,"Woody, Buzz, and the rest of Andy's toys haven...",83.097,14847,7.800,200000000.0,1.067316e+09,NaN,NaN,867316101.0,4.336581
12,24021,Movie,The Twilight Saga: Eclipse,David Slade,"Kristen Stewart, Robert Pattinson, Taylor Laut...",United States of America,2010-06-23,2010,6.204,NaN,...,Bella once again finds herself surrounded by d...,81.800,8829,6.204,68000000.0,6.984913e+08,NaN,NaN,630491347.0,9.271932
13,12155,Movie,Alice in Wonderland,Tim Burton,"Mia Wasikowska, Johnny Depp, Anne Hathaway, He...",United States of America,2010-03-03,2010,6.600,NaN,...,"Alice, now 19 years old, returns to the whimsi...",80.326,14114,6.600,200000000.0,1.025467e+09,NaN,NaN,825467110.0,4.127336
14,73861,Movie,A Serbian Film,Srđan Spasojević,"Srđan 'Žika' Todorović, Sergej Trifunović, Jel...",Serbia,2010-06-16,2010,5.471,NaN,...,Retired porn star Milos leads a normal family ...,74.238,2018,5.471,0.0,0.000000e+00,NaN,NaN,0.0,NaN

In [ ]:
df['ROI']=df['ROI'].replace([np.inf,-np.inf],np.nan)

**Profit and ROI apply only to Movies**
**TV Shows:**

In [ ]:
profit_mean=df['profit'].mean()
loss = df['profit']<0
df['loss']=loss

In [ ]:
df['loss']

0        False
1        False
2        False
3        False
4        False
         ...
15995    False
15996    False
15997    False
15998    False
15999    False
Name: loss, Length: 32000, dtype: bool