#**Netflix Movies and TV Shows: An Exploratory Data Analysis. In this notebook, I will explore the Netflix dataset to understand content trends, popular genres, and the distribution of content across the globe.**

#  Netflix Exploratory Data Analysis (EDA) – Updated till 2025

## 🔹 Introduction
Netflix is one of the largest streaming platforms, offering thousands of Movies and TV Shows globally.  
This project analyzes Netflix data till **2025**, providing more updated insights than traditional 2021 datasets.

## 🔹 Objectives
- Clean and preprocess the dataset
- Explore patterns in Movies vs TV Shows
- Analyze trends across countries and years
- Study popular genres and ratings
- Derive insights on how Netflix’s strategy evolved till 2025

In [17]:
from google.colab import drive
import os

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Set your GitHub Identity (Required for Green Dots)
!git config --global user.email "pankajbarathod9@gmail.com"
!git config --global user.name "Krishna3226"

# 3. Move to your Project Folder (Change 'MyProject' to your folder name)
%cd /content/drive/MyDrive/1230280501028 (1)/Projects/netflix-data-analysis

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/1230280501028 (1)/Projects/netflix-data-analysis

## 🔹 Dataset Description
We have two separate CSV files:
- **Movies dataset**
- **TV Shows dataset**

Each dataset includes:
- `title` – Name of the content  
- `director`, `cast` – Key people involved  
- `country` – Origin country  
- `release_year` – Original release year  
- `date_added` – When added to Netflix  
- `rating` – Age rating (PG, R, TV-MA, etc.)  
- `duration` – Runtime (Movies) or Seasons (TV Shows)  
- `listed_in` – Genres  
- `description` – Short summary

In [2]:
#Importing Necessary Libararies
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#Style for plots
sns.set_style('whitegrid')
plt.style.use('fivethirtyeight')

# Load the Netflix dataset
movies = pd.read_csv("/content/drive/MyDrive/1230280501028 (1)/Projects/Netflix_Analysis/netflix_movies_detailed_up_to_2025.csv")
tv_shows=pd.read_csv("/content/drive/MyDrive/1230280501028 (1)/Projects/Netflix_Analysis/netflix_tv_shows_detailed_up_to_2025.csv")

df=pd.concat([movies,tv_shows],axis=0)
df.columns
print("Shape of Dataset: ",df.shape)
df

Shape of Dataset:  (32000, 18)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000.0,752600867.0
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000.0,839030630.0
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000.0,954305868.0
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,"Animation, Family, Adventure",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000.0,592461732.0
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,"Fantasy, Adventure, Animation, Family",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000.0,494879471.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,284892,TV Show,Sammelanam,NaN,NaN,NaN,2025-02-20,2025,0.000,1 Seasons,"Comedy, Drama",te,Sammelanam is a gripping Telugu web series tha...,3.236,0,0.000,NaN,NaN
15996,277665,TV Show,Anne Shirley,NaN,"Honoka Inoue, Yasunori Matsumoto, Aya Nakamura...",Japan,2025-04-05,2025,0.000,1 Seasons,"Animation, Drama, Family",ja,It's depict Anne's growth from a girl to a wom...,3.558,0,0.000,NaN,NaN
15997,284972,TV Show,Le onde del passato,Giulio Manfredonia,"Anna Valle, Giorgio Marchesi, Irene Ferri, Fau...",NaN,2025-02-19,2025,10.000,1 Seasons,Drama,it,NaN,2.913,1,10.000,NaN,NaN
15998,284613,TV Show,AI히치하이커,NaN,NaN,NaN,2025-02-16,2025,0.000,1 Seasons,NaN,ko,NaN,2.787,0,0.000,NaN,NaN
15999,251815,TV Show,Alex & Laura's Saturday Night Takeaway,NaN,"Alex Bickerton, Lauren Blake",NaN,2025-02-15,2025,0.000,1 Seasons,"Comedy, Family",en,A gameshow hosted by Alex & Laura filled with ...,2.485,0,0.000,NaN,NaN

In [3]:
df.info()
#Checking Number of Missing Values in each Row
missing_values=df.isnull().sum()
print('\n Missing Values:\n','\n',missing_values[missing_values>0])

<class 'pandas.core.frame.DataFrame'>
Index: 32000 entries, 0 to 15999
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       32000 non-null  int64
 1   type          32000 non-null  object
 2   title         32000 non-null  object
 3   director      20903 non-null  object
 4   cast          30639 non-null  object
 5   country       29737 non-null  object
 6   date_added    32000 non-null  object
 7   release_year  32000 non-null  int64
 8   rating        32000 non-null  float64
 9   duration      16000 non-null  object
 10  genres        30919 non-null  object
 11  language      32000 non-null  object
 12  description   28662 non-null  object
 13  popularity    32000 non-null  float64
 14  vote_count    32000 non-null  int64
 15  vote_average  32000 non-null  float64
 16  budget        16000 non-null  float64
 17  revenue       16000 non-null  float64
dtypes: float64(5), int64(3), object(10)
memory usage: 5.6+ MB

 Missing Values:

 director       11097
cast            1361
country         2263
duration       16000
genres          1081
description     3338
budget         16000
revenue        16000
dtype: int64

Here, 7 Columns are there which have Missing Values:
director(object),
cast(object),
country(object),
genre(object),
description(object),
budget(object),
revenue(object),



*   **Duration data is only available for TV Show. for Movies These field is Missing.**
*   **Budget and revenue data is only available for Movies. For TV
Shows, these fields are missing.**

## 🔹 Data Cleaning
Steps performed:
1. Handle missing values
2. Convert `date_added` into datetime
3. Extract useful features (`year_added`, `content_age`)
4. Remove duplicates

In [62]:
# df=df.drop(['season_num','movie_duration'],axis=1)

In [5]:
df=df.drop('duration',axis=1)

In [6]:
df.isnull().sum()

df.fillna({"director":"Unknown",'cast':"Unknown","country":"Unknown",'genres':"Unknown","description":"No Description Available"})

df['budget']=pd.to_numeric(df['budget'])

df['revenue']=pd.to_numeric(df['revenue'])

For TV Shows there are no such columns like revenue and budget. but in movies it is there.so there NaNs in tv shows.

In [61]:
profit=df['revenue']-df['budget']
ROI=profit/df['budget']
df['profit']=profit
df['ROI']=ROI
# df.head(15)

In [8]:
df['ROI']=df['ROI'].replace([np.inf,-np.inf],np.nan)

**Profit and ROI apply only to Movies**

In [9]:
profit_mean=df['profit'].mean()
loss = df['profit']<0
df['loss']=loss

In [10]:
df[df['loss'] == True]

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,language,description,popularity,vote_count,vote_average,budget,revenue,profit,ROI,loss
15,38234,Movie,Undisputed III: Redemption,Isaac Florentine,"Scott Adkins, Mykel Shannon Jenkins, Mark Ivan...",United States of America,2010-04-17,2010,7.517,"Action, Thriller, Crime, Drama",en,"Russian inmate Boyka, now severely hobbled by ...",71.837,925,7.517,3000000.0,282548.0,-2717452.0,-0.905817,True
34,22538,Movie,Scott Pilgrim vs. the World,Edgar Wright,"Michael Cera, Mary Elizabeth Winstead, Ellen W...","Japan, United Kingdom, United States of America",2010-08-12,2010,7.491,"Action, Comedy, Romance",en,"As bass guitarist for a garage-rock band, Scot...",39.321,7985,7.491,85000000.0,51691156.0,-33308844.0,-0.391869,True
37,43947,Movie,I Spit on Your Grave,Steven R. Monroe,"Sarah Butler, Jeff Branson, Tracey Walter, And...",United States of America,2010-06-17,2010,6.500,"Thriller, Crime, Horror",en,"A beautiful woman from the city, Jennifer Hill...",38.125,2344,6.500,2000000.0,572809.0,-1427191.0,-0.713596,True
43,46738,Movie,Incendies,Denis Villeneuve,"Lubna Azabal, Mélissa Désormeaux-Poulin, Maxim...","Canada, France",2010-09-17,2010,8.100,"Drama, War, Mystery",fr,A mother's last wishes send twins Jeanne and S...,35.555,2830,8.100,6800000.0,6788659.0,-11341.0,-0.001668,True
45,43949,Movie,Flipped,Rob Reiner,"Madeline Carroll, Callan McAuliffe, Rebecca De...",United States of America,2010-08-06,2010,8.016,"Romance, Drama",en,"When Juli meets Bryce in the second grade, she...",34.886,3062,8.016,14000000.0,4324817.0,-9675183.0,-0.691084,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,1439948,Movie,Serlasanha,"Kelvin Bohn, Eduardo Wilborn",NaN,Brazil,2025-02-27,2025,0.000,"Animation, Science Fiction, Thriller, Mystery",pt,NaN,5.379,0,0.000,17.0,0.0,-17.0,-1.000000,True
15922,1130863,Movie,Belle,Benoît Jacquot,"Charlotte Gainsbourg, Guillaume Canet, Pauline...","Belgium, France",2025-03-13,2025,0.000,"Thriller, Drama",fr,A couple have a peaceful existence in a small ...,5.296,0,0.000,3000000.0,0.0,-3000000.0,-1.000000,True
15959,1317288,Movie,Marty Supreme,Josh Safdie,"Timothée Chalamet, Gwyneth Paltrow, Tyler, The...","Finland, United States of America",2025-12-25,2025,0.000,Drama,en,A fictional story set in the world of 1950s pi...,5.096,0,0.000,70000000.0,0.0,-70000000.0,-1.000000,True
15966,1282125,Movie,Delfino's Journey,Arthur Allan Seidelman,"Fernando Paez, Julio Macias, Sal Lopez, Giovan...",United States of America,2025-04-10,2025,0.000,"Crime, Drama, Thriller",en,On the run from a bloodthirsty Mexican drug ca...,5.067,0,0.000,8600000.0,0.0,-8600000.0,-1.000000,True
15971,1424464,Movie,Dollar Babys,"Remi Alfallah, Megan Haly","Shannon Haly, Kyra Green, Natasha Farkas, Mega...",NaN,2025-02-25,2025,0.000,"Drama, Comedy",en,"Stuck for cash, a queer couple venture into th...",5.047,0,0.000,35.0,0.0,-35.0,-1.000000,True

In [11]:
df_sorted=df.sort_values(by='release_year',ascending=True)
df_sorted.iloc[1]

show_id                                                     73861
type                                                        Movie
title                                              A Serbian Film
director                                         Srđan Spasojević
cast            Srđan 'Žika' Todorović, Sergej Trifunović, Jel...
country                                                    Serbia
date_added                                             2010-06-16
release_year                                                 2010
rating                                                      5.471
genres                                    Crime, Horror, Thriller
language                                                       sr
description     Retired porn star Milos leads a normal family ...
popularity                                                 74.238
vote_count                                                   2018
vote_average                                                5.471
budget                                                        0.0
revenue                                                       0.0
profit                                                        0.0
ROI                                                           NaN
loss                                                        False
Name: 14, dtype: object

In [15]:
df_sorted['date_added']=pd.to_datetime(df_sorted['date_added'],errors='coerce')
df_sorted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32000 entries, 15 to 15000
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       32000 non-null  int64
 1   type          32000 non-null  object
 2   title         32000 non-null  object
 3   director      20903 non-null  object
 4   cast          30639 non-null  object
 5   country       29737 non-null  object
 6   date_added    32000 non-null  datetime64[ns]
 7   release_year  32000 non-null  int64
 8   rating        32000 non-null  float64
 9   genres        30919 non-null  object
 10  language      32000 non-null  object
 11  description   28662 non-null  object
 12  popularity    32000 non-null  float64
 13  vote_count    32000 non-null  int64
 14  vote_average  32000 non-null  float64
 15  budget        16000 non-null  float64
 16  revenue       16000 non-null  float64
 17  profit        16000 non-null  float64
 18  ROI           4847 non-null   float64
 19  loss          32000 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(7), int64(3), object(8)
memory usage: 4.9+ MB

In [74]:
x=df_sorted[(df_sorted['revenue']==0) & (df_sorted['budget']==0)]
len(x)

9048

In [ ]:
!git add .
!git commit -m "Done work with profit/loss analysis for further work.only 44% data is there for Profit/loss calculation"
!git push origin main